// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.get("FIREBASE_WEB_API_KEY"),
    appId: '1:788816865859:web:572bb84f0875e1384f82f6',
    messagingSenderId: '788816865859',
    projectId: 'hotline-3ecbe',
    authDomain: 'hotline-3ecbe.firebaseapp.com',
    storageBucket: 'hotline-3ecbe.appspot.com',
    measurementId: 'G-XQPM70NY08',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.get("FIREBASE_ANDROID_API_KEY"),
    appId: '1:788816865859:android:a3001e69ae9410794f82f6',
    messagingSenderId: '788816865859',
    projectId: 'hotline-3ecbe',
    storageBucket: 'hotline-3ecbe.appspot.com',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.get("FIREBASE_IOS_API_KEY"),
    appId: '1:788816865859:ios:6045aee9050f91f14f82f6',
    messagingSenderId: '788816865859',
    projectId: 'hotline-3ecbe',
    storageBucket: 'hotline-3ecbe.appspot.com',
    iosClientId: '788816865859-165beiaepl45bevnjn18dqmqv9pdsvi0.apps.googleusercontent.com',
    iosBundleId: 'com.hotline.v2.hotlineV2',
  );
}
